### ISSUE TITLE
Switch to complete nom parser from current streaming ones

### ISSUE THREAD

**Issue by jannschu** [rusticata/der-parser#20]
Hi,

der-parser currently uses the streaming variant of the nom parsers. Version 5 now offers complete variants.

The streaming versions make using optionals `opt!` and `many1!` etc. a bit cumbersome. There are a few issues in the nom repo with examples for such problems.

At least for the application in x509-parser (and other cryptography realated parsers in general) the parsing of partial data is not necessary (?).

To ease usage (and increase performance?) I suggest to switch to the complete nom parsers.

**Comment by chifflier** [comment]
Hi,
Agreed, the switch to `complete` variants is now possible, and should help improving code readability. It will just require a lot of testing, since possible bugs are quite hard to track.

**Comment by chifflier** [comment]
All parsers are now based on functions. Finally!
Only a few macros have been left, for backwards compatibility.
