### ISSUE TITLE
It would be good if .as_u64() could parse BitStrings into numbers, too

### ISSUE THREAD

**Issue by p1-mmr** [rusticata/der-parser#28]
Hello,

I think that it would be useful if [`.as_u64()`](https://docs.rs/der-parser/4.1.0/src/der_parser/ber/ber.rs.html#436) could parse `BIT STRING` values into numbers, too, as BitStrings turns out to be sometimes used as enumerated integer values in ASN.1 definitions.

I will maybe make a pull request for that if the maintainer is OK.

**Comment by chifflier** [comment]
That looks great for the cases the bitstring is indeed the representation of a small integer. I applied #29, thanks (so closing issue)

For other cases, I'm wondering if the `bitvec` crate would be a good crate to use to abstract values.
