### ISSUE TITLE
Integers are handled incorrectly

### ISSUE THREAD

**Issue by jamespharaoh** [rusticata/der-parser#3]
You decode integers as hex strings, but they are not encoded this way. Also, the error seems to get swallowed up. I can provide more information later, but for now I've simply commented out the integer branch in `der_read_element_content_as` and get these as an unknown.

**Comment by chifflier** [comment]
Hi,
The function name might be misleading, but integers are parsed as u64 (see the unit tests in `src/der.rs`). Since Der integers can be larger, that can overflow.
Is that what your are encountering ?

**Comment by jamespharaoh** [comment]
they are processed as hex here - https://github.com/rusticata/der-parser/blob/master/src/der.rs#L490. i am also aware that they can overflow, and in my case this prevents a simple fix because it's 13 octets. i am trying to decode a DER encoded certificate extracted from rustls during an ssl session and what i'm seeing is that the integer doesn't get parsed correctly, which in turn causes the sequence which the integer is part of to stop being processed entirely. i'll post the certificate here so you can try it yourself.

**Comment by jamespharaoh** [comment]
Here it is, base64 encoded:

> MIIFczCCBFugAwIBAgIRAJge8uecfqQXpsr+wCXGso4wDQYJKoZIhvcNAQEL
> BQAwgZAxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0
> ZXIxEDAOBgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1p
> dGVkMTYwNAYDVQQDEy1DT01PRE8gUlNBIERvbWFpbiBWYWxpZGF0aW9uIFNl
> Y3VyZSBTZXJ2ZXIgQ0EwHhcNMTYwNzAyMDAwMDAwWhcNMTcwNzAyMjM1OTU5
> WjBmMSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxHTAbBgNV
> BAsTFFBvc2l0aXZlU1NMIFdpbGRjYXJkMSIwIAYDVQQDDBkqLndlbGxiZWhh
> dmVkc29mdHdhcmUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
> AQEAtvDFS0fXeNBUAXwMmBVawBC+63BANnGADzZ4H6gqwF/OnnfbaedLVyGR
> kBxjRG9GIStpTmNfdNrvVCoaduxKT1+QNxBOw9ZQ8iHkKZMCuhALB2CogSt0
> CwtdEi8zVLoVQ1QpieNIjOqvtkz99DFuE5aBAw0Sun530YoGXJ0s+9z8lK2D
> 6Ie/CjBQoyCrNl8wYYc3XubU96b2+u+CM2QyqkOkjM1LmoCGxN+9+DkOLIHF
> Gm02qxQnLzB8OY+JY7sTjozik4PzKgVoXLJXD2MDaM1ED6j/bf1WTPV9ObZQ
> jNr691acQMj6Qqo/NKjXZORdlpTgnRGClM8hPvWe5ojNFQIDAQABo4IB7zCC
> AeswHwYDVR0jBBgwFoAUkK9qOpRaC9iQ6hJWc99DtDoo2ucwHQYDVR0OBBYE
> FL7Om/6OQcKJ3shK/Csv5y98hemFMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMB
> Af8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBPBgNVHSAE
> SDBGMDoGCysGAQQBsjEBAgIHMCswKQYIKwYBBQUHAgEWHWh0dHBzOi8vc2Vj
> dXJlLmNvbW9kby5jb20vQ1BTMAgGBmeBDAECATBUBgNVHR8ETTBLMEmgR6BF
> hkNodHRwOi8vY3JsLmNvbW9kb2NhLmNvbS9DT01PRE9SU0FEb21haW5WYWxp
> ZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3JsMIGFBggrBgEFBQcBAQR5MHcwTwYI
> KwYBBQUHMAKGQ2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NPTU9ET1JTQURv
> bWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5jcnQwJAYIKwYBBQUHMAGG
> GGh0dHA6Ly9vY3NwLmNvbW9kb2NhLmNvbTA9BgNVHREENjA0ghkqLndlbGxi
> ZWhhdmVkc29mdHdhcmUuY29tghd3ZWxsYmVoYXZlZHNvZnR3YXJlLmNvbTAN
> BgkqhkiG9w0BAQsFAAOCAQEAQQjXkL++29ZyxVWQw5/Hc8dKrRROBS7hZi0v
> MXluLoxnnz2W2OULUH9uD5OBmvz22XYB0uKFKvFZ4kYerurth/aYa5vfANsn
> ZlmZMY8FdRq9i8r5aKpMME+/nKhLLuaCzJLgFzJra2FVypKSccVJUgGHJTks
> s+XUKPHewWeeAEx1WzxyFUuJ+kqA0L01Q1FcSry3Zo8ZYRhhz6saCVJyAziU
> NjUpeAhl5E7zCa0DawkgUZUYED3LQAPmPdUjEKcEUPcJedW6YOTuDYF1BS8t
> 5Uj4R8nhM0yob//uh/n5hhXN0RNbl/QcEJ7FdDggbhyj88hxcLna6e0fl53R
> 8Cs6QA==
>

**Comment by jamespharaoh** [comment]
here's a fork i created to get my project to work

https://github.com/jamespharaoh/der-parser
