### ISSUE TITLE
der-parser 6.0 roadmap

### ISSUE THREAD

**Issue by chifflier** [rusticata/der-parser#37]
*placeholder for now, roadmap is not defined yet*

Some ideas:
- Add `&[u8]` to error type ? (consequence: `BerError` will now have a lifetime, but we will be able to tell *where the parsing failed*)
- Use `Cow<'a, [u8]>` everywhere so `BerObject` can own data
- Support BER constructed strings. This may be done either be reconstructing the data (requiring owned data, see above), ropes (new dependency, for ex the `bytes` crate), or new/recursive object types (resulting in a complex API)

**Comment by chifflier** [comment]
Adding `no_std` support to the 6.0 roadmap (PR in #50 )

**Comment by naveedpash** [comment]
Question: you guys aren't using `serde` to implement serialization?
