### ISSUE TITLE
[Question] In `BerObjectContent::BitString` what is the first elem of the pair?

### ISSUE THREAD

**Issue by Geobert** [rusticata/der-parser#41]
Hi,

thank you for this crate!

I'm guessing that in https://docs.rs/der-parser/5.0.0/der_parser/ber/enum.BerObjectContent.html#variant.BitString 
the first element of the pair is the number of unused bits, but I wanted to ask to be sure :)

Am I correct?

(maybe the doc should have an entry for each variant of `BerObjectContent`?)

Thanks!

**Comment by chifflier** [comment]
Hi,
You're correct, the first argument is the number of unused bits.
I'll see to improve the documentation :)

**Comment by Geobert** [comment]
Thanks, closing this then :)
