### ISSUE TITLE
asn1 length

### ISSUE THREAD

**Issue by wisespace-io** [rusticata/der-parser#5]
Is there any way to get the asn1 length? It seems to be available in the DerElementHeader

**Comment by chifflier** [comment]
Hi,

The length is not stored (because the header is not kept after reading fields) currently. What is your use case ? Copying it or storing the header would not be difficult, but it would require to change the API

**Comment by wisespace-io** [comment]
I developed a method to infer the size, so it is not needed. However, how I would access the content (vec) from the DerObject below?

 DerObject { class: 0, structured: 0, tag: 2, content: Integer([0, 1, 2 ,3 4, 5]) }

**Comment by chifflier** [comment]
It depends if you need to get the integer, or want to access the bytes.

The integer can be obtained using the `as_u32()` method (but will return an error if the integer is greater than 2^32) or `as_bigint()`

If you need to access the raw vector, you need to match the object content, either using a `match` or a `let if`:
```rust
if let DerObjectContent::Sequence(ref v) = der_obj.content {
  // use v
}
```
or
```rust
match der_obj.content {
  DerObjectContent::Integer(ref v) => { // use v
  },
  _ => (),
}
```

**Comment by wisespace-io** [comment]
Thank your for the explanation
